In [4]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [5]:
# charger les données
data = load_iris()
x = data.data
y = data.target

In [9]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
# Diviser les données
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [14]:
#Créer et entrainer le modèle svm
svm = SVC(kernel='rbf', C=1.0, gamma='scale')
svm.fit(x_train, y_train)

# Evaluer le modele
y_pred = svm.predict(x_test)
print("Accuracy", accuracy_score(y_test, y_pred))
print("confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy 1.0
confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
